#!/bin/sh

if ischroot; then
	# native fomat
	#depmod $(dpkg-query --show --showformat='${Version}' linux-image-n900 | cut -d '-' -f1)
	# quilt format
	depmod $(dpkg-query --show --showformat='${Version}' linux-image-n900 | cut -d '-' -f1)
else
	depmod -a
fi
